nodeLinker: node-modules

# Lock all form-data versions to 4.0.4 due to https://cwe.mitre.org/data/definitions/330.html
packageExtensions:
  "@backstage/cli@*":
    dependencies:
      form-data: ^4.0.4
  axios@*:
    dependencies:
      form-data: ^4.0.4
  jsdom@*:
    dependencies:
      form-data: ^4.0.4

yarnPath: .yarn/releases/yarn-4.9.3.cjs
