app:
  title: Apono Example App
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  cors:
    origin: http://localhost:3000

  csp:
    frame-src: ["'self'", "http://localhost:9011"]

apono:
  clientUrl: http://localhost:9011
  supportLinks:
    - label: Support
      value: Go here
      url: https://example.com/support
    - label: Documentation
      value: Go here
      url: https://example.com/docs
